export DATAVERSE_SERVER_URL=
export DATAVERSE_USERNAME_FOR_PERM_TEST=
export DATAVERSE_TEST_USER_USERNAME=

# For built in login testing
export DATAVERSE_TEST_USER_PASSWORD_BUILTIN=

# For sso login testing
export DATAVERSE_SSO_OPTION_VALUE=